### ISSUE TITLE
BBB system space Issue

### ISSUE THREAD

**Issue by SantiagoGarza96** [MXET/SCUTTLE#11]
![mxet 300 space issue](https://user-images.githubusercontent.com/20343153/53993141-26489680-40f4-11e9-92e1-40b024c2aa37.PNG)

I get this Issue when I try to use apt-get install "program name" to download programs. Any idea on checking and managing the BBB system storage.

**Comment by ansarid** [comment]
@SantiagoGarza96 Try running these commands:

```
cd /opt/scripts/tools
git pull
sudo ./grow_partition.sh
sudo reboot
```

**Comment by SantiagoGarza96** [comment]
Thank you very much it worked. If possible can you explain what this did?

**Comment by dmalawey** [comment]
Daniyal found the fix, not me but I just googled “Linux grow_partition” and found this:

https://elinux.org/Beagleboard:Expanding_File_System_Partition_On_A_microSD

**Comment by ansarid** [comment]
@SantiagoGarza96 Sure!

```
cd /opt/scripts/tools
```
Moves you into the ```/opt/scripts/tools``` directory.
```
git pull
```
Since the directory you are in is a git repository that comes already downloaded to the BeagleBone it may be out of date. ```git pull``` updates the repository. When you run the command you will see the link https://github.com/RobertCNelson/boot-scripts show up since that is the original location of the repository.
```
sudo ./grow_partition.sh
```
This command runs the shell script ```grow_partition.sh``` which you can open and read through but basically gets the size of the sd card it is on and then expands the root partition to fill that space.
```
sudo reboot
```
Reboots the BeagleBone.
