### ISSUE TITLE
X11 Forwarding from BBB Issue

### ISSUE THREAD

**Issue by d-belleza** [MXET/SCUTTLE#23]
When trying to ssh using X11 forwarding, we get an error message:
X11 forwarding request failed on channel 0

We have tried to modify the sshd_config file by changing the lines to:
X11Forwarding yes
X11UseLocalhost no

We do not know how to allow X11 forwarding to show the captured frame from OpenCV.

**Comment by ansarid** [comment]
You may not have the X11 server installed.
Try ```sudo apt-get install xorg```.

**Comment by d-belleza** [comment]
Trying to install xorg and run into the issue of
`You don't have enough free space in /var/cache/apt/archives/.`

**Comment by ansarid** [comment]
Please try:
```
  cd /opt/scripts/tools
  git pull
  sudo ./grow_partition.sh
```

**Comment by dlnash96** [comment]
The solution you posted for increasing the partition size worked. However, we now get the error message: 

> "X11 connection rejected because of wrong authentication."

This happens when using a very simple script that calls xeyes on the beaglebone. 

`import os`
`os.system("xeyes")`


![Screen Shot 2019-04-08 at 4 07 22 PM](https://user-images.githubusercontent.com/31893695/55756970-6b742700-5a18-11e9-845e-9c3c594132c0.png)

**Comment by ansarid** [comment]
You cannot call a gui application using os.system() on a remote server because though X11 works on your beaglebone it will not forward the gui through the X11 display.
