### ISSUE TITLE
USB Audio Issue 

### ISSUE THREAD

**Issue by RMC-800** [MXET/SCUTTLE#42]
# I lose connection from the gamepad and the speaker stops working when I run L3_drive_mt.py with both the USB dongle and a USB audio input device connected to the USB hub. 

# These are the steps to reproduce this error. 

#1). Connect the gamepad dongle and the USB audio to the USB hub and make sure the hub is connected to the BeagleBone. 
#2). Run L3_drive_mt.py and check the functionality of the wheel control by moving the joystick. This should work fine. 
#3). Press a button, such as button (X), to make SCUTTLE talk. May hear SCUTTLE say something once, but will cause gamepad to stop controlling wheels or send any more commands for speaking. 
#4). Will have to open up a new terminal to cancel as this prevents me from stopping the program via ctrl^C.
#5). No error outputs are produced.

**Comment by dmalawey** [comment]
If you want to use DriveMT, please confirm you have latest versions of all dependent files.  (almost every python file in basics folder).   The drivers for bmp have to be working as well.  As you can see if you review the speaking loop, this loop accesses some sensors now to produce feedback.  Probably there's an issue with the speaking loop on your bot.

I'm planning to take down the DriveMT file since it uses hardware not included on all robots.  It will be replaced eventually by a simple multithreading example.
